"""The replay matrix: every public purchase, its decision and message (docs/replay-matrix.md).

    make matrix    # python -m oneguard.replay.matrix --out ../docs/replay-matrix.md

Every scenario through the real pipeline (``runner.decide_all``: a fresh seeded store and
``StoreLedger`` per run, every engine lane registered) with its policy fixture, once with
soft signals on (the ``keywords`` backend, whatever ``ONEGUARD_SOFT_SIGNALS`` says, so the
file does not depend on the shell) and once off. Step-ups are never answered (CLAUDE.md
rule 6), so an oracle row that depends on an earlier answer is read in its unanswered
branch, as tests/test_replay_via_api.py does. The output is deterministic: no date or
commit, so tests/test_replay_matrix.py can fail when the committed file is stale.

Exits 1 when an outcome differs from the oracle or signals off moves an outcome.
Test tooling like the rest of ``replay/``: it reads scenario ids, the policy fixtures and
the oracle.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

from oneguard.engine import signals
from oneguard.replay.events import Pack
from oneguard.replay.oracle import unanswered_branch, unanswered_outcomes
from oneguard.replay.runner import Decided, _cell, decide_all, load_policy

BACKEND = Path(__file__).resolve().parents[2]
POLICIES = BACKEND / "tests" / "fixtures" / "policies"
DOC = BACKEND.parent / "docs" / "replay-matrix.md"


@dataclass(frozen=True)
class Row:
    decided: Decided
    expected: str  # the oracle's outcome, step-ups unanswered
    off: str  # the outcome with soft signals off


@contextmanager
def _keyword_signals() -> Iterator[None]:
    """Soft signals on means the deterministic keyword backend for the matrix."""
    backend = signals.BACKEND
    signals.BACKEND = signals.KeywordSignals()
    try:
        yield
    finally:
        signals.BACKEND = backend


def build(pack: Pack, policies: Path = POLICIES) -> list[Row]:
    rows = []
    with _keyword_signals():
        for scenario_id in pack.scenario_ids():
            policy = load_policy(policies / f"{scenario_id}.yaml", mandate_id=f"TM_REPLAY_{scenario_id}")
            expected = unanswered_outcomes(scenario_id)
            off = {d.source_id: d.outcome for d in decide_all(pack, scenario_id, policy, signals=False)}
            for decided in decide_all(pack, scenario_id, policy, signals=True):
                rows.append(Row(decided, expected[decided.source_id], off[decided.source_id]))
    return rows


def problems(rows: list[Row]) -> list[str]:
    """Every row that differs from the oracle or moves with signals off."""
    found = []
    for r in rows:
        d = r.decided
        if d.outcome != r.expected:
            found.append(f"{d.source_id}: {d.outcome}, the oracle says {r.expected}")
        if d.outcome != r.off:
            found.append(f"{d.source_id}: {d.outcome} with signals on, {r.off} with signals off")
    return found


def markdown(pack: Pack, rows: list[Row]) -> str:
    total = len(rows)
    totals = Counter(r.decided.outcome for r in rows)
    matched = sum(r.decided.outcome == r.expected for r in rows)
    identical = sum(r.decided.outcome == r.off for r in rows)
    read = [(s, unanswered_branch(s)) for s in pack.scenario_ids()]
    branches = "; ".join(f'{s} "{b.label}"' for s, b in read if b is not None) or "none"
    lines = [
        "# Replay matrix with messages",
        "",
        (
            f"All {total} public purchases through the real pipeline (`pipeline.decide_event`), one run per "
            "scenario with a fresh ledger. Generated by `make matrix` (`backend/oneguard/replay/matrix.py`); "
            "`tests/test_replay_matrix.py` fails when this file is stale."
        ),
        "",
        "| | |",
        "|---|---|",
        "| Ledger | store (`engine.ledger.StoreLedger`, temp SQLite) |",
        (
            "| Soft signals | on (`ONEGUARD_SOFT_SIGNALS=keywords`); a second run with signals off gives "
            "identical outcomes |"
        ),
        f"| Step-ups | never answered; oracle branches read: {branches} |",
        f"| Outcomes | {totals['approve']} approve, {totals['decline']} decline, {totals['step_up']} step_up |",
        f"| Oracle match | {matched}/{total} |",
        f"| Signals off vs on | {identical}/{total} identical outcomes |",
        "",
        "| ID | Decision | Reason codes | Message |",
        "|---|---|---|---|",
    ]  # fmt: skip
    for r in rows:
        d = r.decided
        lines.append(f"| {d.source_id} | {d.outcome} | {', '.join(d.reason_codes)} | {_cell(d.message)} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="The replay matrix as markdown (docs/replay-matrix.md).")
    parser.add_argument("--policies", type=Path, default=POLICIES, help="folder of <scenario>.yaml policies")
    parser.add_argument("--out", type=Path, help="write the matrix here instead of stdout")
    args = parser.parse_args(argv)
    pack = Pack.load()
    rows = build(pack, args.policies)
    text = markdown(pack, rows)
    if args.out:
        args.out.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    found = problems(rows)
    for problem in found:
        print(problem, file=sys.stderr)
    return 1 if found else 0


if __name__ == "__main__":
    raise SystemExit(main())
