"""Replay matrix with messages: the 45 public purchases through the real pipeline (docs/replay-matrix.md).

    python scripts/replay_matrix.py > ../docs/replay-matrix.md

One run per scenario on a fresh ``StoreLedger`` (temp SQLite), with the scenario's policy
fixture, soft signals on (``keywords``); a second run with signals off must give the same
outcomes. A scenario with ``depends`` rows answers the step-up they name with its
"pending" branch when there is one, else its "declined or expired" branch, so every row
has one outcome. Reuses the oracle test's helpers, so the matrix and the oracle test
replay the same way. Never touches ``ONEGUARD_DATABASE_URL``.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

from oneguard.pipeline import PipelineContext, decide_event
from oneguard.replay.events import Pack, build_events
from oneguard.store import seed as seed_module
from oneguard.store.db import make_engine, session
from oneguard.store.history import StoreHistoryIndex
from tests.test_oracle import (
    NOW,
    ORACLE,
    Branch,
    branches,
    expected_outcome,
    fresh_ledger,
    to_policy,
)

BRANCH_PREFERENCE = ("pending", "decline")


def _branch(scenario_id: str) -> Branch | None:
    found = [b for b in branches(scenario_id) if b is not None]
    for answer in BRANCH_PREFERENCE:
        for branch in found:
            if branch.answer == answer:
                return branch
    return found[0] if found else None


def _run(pack: Pack, history: StoreHistoryIndex, scenario_id: str, branch: Branch | None,
         signals: bool, folder: Path) -> list[tuple[str, str, list[str], str]]:  # fmt: skip
    os.environ["ONEGUARD_SOFT_SIGNALS"] = "keywords" if signals else "off"
    policy = to_policy(scenario_id)
    rows = []
    with fresh_ledger("store", history, folder) as ledger:
        ctx = PipelineContext(policy=policy, ledger=ledger, history=history,
                              run_id=f"matrix-{scenario_id}", signals_enabled=signals)  # fmt: skip
        for event in build_events(pack, scenario_id, mandate_id=policy.mandate_id, now=NOW):
            engine, explanation, _ = decide_event(event, ctx)
            auth = event["authorization"]
            source_id = auth["source_authorization_id"]
            rows.append((source_id, engine.outcome, engine.reason_codes, explanation.message))
            answers = branch is not None and branch.authorization_id == source_id
            if answers and engine.outcome == "step_up" and branch.answer != "pending":
                ledger.resolve(auth["authorization_id"], branch.answer, "customer", NOW)
    return rows


def main() -> None:
    pack = Pack.load()
    with tempfile.TemporaryDirectory() as tmp:
        folder = Path(tmp)
        engine = make_engine(f"sqlite:///{folder / 'history.sqlite'}")
        seed_module.run(engine=engine)
        with session(engine) as s:
            history = StoreHistoryIndex.load(s)
        engine.dispose()

        table, used, matched, identical, total = [], [], 0, 0, 0
        for scenario_id in sorted(ORACLE["scenarios"]):
            branch = _branch(scenario_id)
            if branch is not None:
                used.append(f'{scenario_id} "{branch.label}"')
            on = _run(pack, history, scenario_id, branch, True, folder)
            off = _run(pack, history, scenario_id, branch, False, folder)
            expected = {r["id"]: expected_outcome(r, branch, ORACLE["defaults"])
                        for r in ORACLE["scenarios"][scenario_id]["purchases"]}  # fmt: skip
            for (source_id, outcome, codes, message), off_row in zip(on, off, strict=True):
                total += 1
                matched += expected[source_id] == outcome
                identical += off_row[1] == outcome
                table.append(f"| {source_id} | {outcome} | {', '.join(codes)} | {message.replace('|', '/')} |")

    head = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True,
                          cwd=BACKEND, check=False).stdout.strip() or "unknown"  # fmt: skip
    print("# Replay matrix with messages\n")
    print(f"All {total} public purchases through the real pipeline (`pipeline.decide_event`), one run per "
          "scenario with a fresh ledger. Generated by `backend/scripts/replay_matrix.py`.\n")  # fmt: skip
    print("| | |\n|---|---|")
    print(f"| Base commit | `{head}` |")
    print(f"| Date | {datetime.now(UTC):%Y-%m-%d} |")
    print("| Ledger | store (`engine.ledger.StoreLedger`, temp SQLite) |")
    print("| Soft signals | on (`ONEGUARD_SOFT_SIGNALS=keywords`); a second run with signals off gives "
          "identical outcomes |")  # fmt: skip
    print(f"| Branches used | {'; '.join(used) or 'none'} |")
    print(f"| Oracle match | {matched}/{total} |")
    print(f"| Signals off vs on | {identical}/{total} identical outcomes |\n")
    print("| ID | Decision | Reason codes | Message |\n|---|---|---|---|")
    print("\n".join(table))


if __name__ == "__main__":
    main()
